name: Build and Push to ECR

on:
  push:
    branches:
      - staging
      - master

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: get commit tag
        id: get_tag
        run: |
          echo "::set-output name={IMAGE_TAG}::git describe --tags --always"
          echo $IMAGE_TAG

      #- name: build, tag, and push image to Amazon ECR production
       # if: github.ref == 'refs/heads/master'
        #env:
         # ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry}}
          #ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          #IMAGE_TAG: ${{ steps.get_tag.outputs }}
        #run: |
         # echo $IMAGE_TAG
          #docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          #docker push $ECR_REGISTRY/$ECR_REGISTRY:$IMAGE_TAG 
    



